### ISSUE TITLE
Incorporate ineffassign tool into our CI job (linter)

### ISSUE THREAD

**Issue by tisnik** [RedHatInsights/insights-operator-utils#13]
https://github.com/gordonklaus/ineffassign

**Comment by bond95** [comment]
Any problem with that issue?

**Comment by tisnik** [comment]
I'd like this issue will be created in JIRA :)

**Comment by bond95** [comment]
Ok 🙂

**Comment by tisnik** [comment]
Already included -> closing this issue :)
