### ISSUE TITLE
Unify naming of Send* functions

### ISSUE THREAD

**Issue by Bee-lee** [RedHatInsights/insights-operator-utils#38]
The current naming of the Send* functions is not unified, therefore it might be a little confusing when used in other apps. 
For example, reading the code in insights-results-aggregator, you can immediately tell what HTTP Code is sent when you use `responses.SendInternalServerError` or `responses.SendCreated`, but you can't really tell which code is sent when you use `responses.SendResponse` and `responses.SendError`

Acceptance criteria:
- `SendResponse` renamed to `SendOk`
- `SendError` renamed to `SendBadRequest`
- Created pull requests in other applications with these changes implemented and waiting for this to be merged

**Comment by tisnik** [comment]
@Bee-lee should be close this one please?

**Comment by Bee-lee** [comment]
@tisnik Sure, it's done, I guess I forgot to close
