### ISSUE TITLE
Make SendResponse accept an HTTP Status

### ISSUE THREAD

**Issue by Bee-lee** [RedHatInsights/insights-operator-utils#7]
As of now, there are separate functions for different status codes and the only advantage this solution brings to the table is improved readability by a teeny-tiny bit in the app that's gonna use this.

The problem is that some functions for some statuses are missing, such as `404`, creating more problems than it solved. Obviously we could create functions for most of the used statuses, but I think a better solution would be to make `SendResponse` accept an HTTP Status and change the calls in the apps. We could keep the separate functions for convenience.

The change in calling would be from 
`responses.SendCreated(...)`
to
`responses.SendResponse(http.StatusCreated, ...)`

Refactor of the usage of `setDefaultContentType` could also be done in this change with little effort. 

Acceptance criteria:
- `SendResponse` accepts the status codes
- usage of `setDefaultContentType` refactored

**Comment by Sergey1011010** [comment]
Seems that the issue can be closed according to https://github.com/RedHatInsights/insights-operator-utils/pull/8

**Comment by bond95** [comment]
Yes, it was fixed
